AWSTemplateFormatVersion: 2010-09-09
Description: Create Resources
Parameters:
  DataBucketName:
    Type: String
    Default: "sensor-data-keisuke-nakata"
    Description: Sensor raw data bucket

Resources:
  DataS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref DataBucketName
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

Outputs:
  S3BucketName:
    Value: !Ref DataBucketName