AWSTemplateFormatVersion: "2010-09-09"
Resources:
  CloudFormationServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: create-sqs-resource
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: 
                  - s3:*
                  - apigateway:*
                  - dynamodb:*
                  - cloudfront:*
                  - iot:*
                  - iotevents:*
                  - sagemaker:*
                  - amplifybackend:*
                  - lambda:*
                Resource: 
                  - "*"