os: linux
dist: bionic

matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=lint
    # py3.6 build keeps failing, I have no idea why
    #- python: "3.6"
    #  env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38

cache:
  directories:
    - $HOME/.cache/pip
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libbluetooth-dev 
install: pip install -U tox coveralls
language: python
script: tox
after_success: coveralls